### ISSUE TITLE
RetryException doesn't have Retry-After value

### ISSUE THREAD

**Issue by andrew-potachits** [dropbox/dropbox-sdk-dotnet#10]
according to Error handling section of [documentation](https://www.dropbox.com/developers/documentation/http/documentation), HTTP error 429 provides retry time in Retry-After header

RetryException doesn't have this information, so when API call throws RetryException there are no way to know when its legal to do the next call.

**Comment by qimingyuan** [comment]
In v2.3.6 we introduced a subclass of RetryException called RateLimtException which contains a RetryAfter field. Client can do proper backoff based on this value. For general RetryExcepton which mostly caused by transient failure, the sdk already does a certain number of retries and it's up to the client to decide whether continue retrying or not.
