### ISSUE TITLE
I could not reference it in .net framework 4.0 version

### ISSUE THREAD

**Issue by krishnaramuu** [dropbox/dropbox-sdk-dotnet#16]
Even though I installed the Dropbox.Api from nuget to my project, it is still showing the error that it could not reference the assembly for dropbox.api. what would be the reason, I just checked with framework version and i am using 4.0 for which i am using the same version dll. please help me out what is wrong here...

**Comment by scobbe** [comment]
Have you successful built the project?

**Comment by krishnaramuu** [comment]
No, i could not if dropbox.api is imported in the class.

**Comment by scobbe** [comment]
Ok, please confirm that you took the following steps:

1. Created VS project
2. Right click on project > Manage NuGet Packages...
3. Search for 'Dropbox v2 API', then click Install
4. Confirm that 'Dropbox.Api` is a listed reference under 'References' in your project (also confirm under its Reference Properties that the reference points to a valid .dll file in the 'packages' directory in your project folder (in the file system)) 

If there was an issue with any of these steps, please reply with a detailed description of the issue.

Otherwise, if you can confirm that you took all of these steps successfully, please send us relevant screen shots of your project (with 'References' fully expanded and with a line of test code invoking a Dropbox API v2 class) and we will try and debug the issue further. 

Thank you!

**Comment by krishnaramuu** [comment]
Yes, i have done the same way as you said. please check the reference properties and the folder path as well.
![db4](https://cloud.githubusercontent.com/assets/3852296/13536354/6f7e9c64-e265-11e5-9f94-9e76b1ba351a.png)


![db1](https://cloud.githubusercontent.com/assets/3852296/13536297/22b72e5a-e265-11e5-83bf-1e88bc1ed6b0.png)
![db2](https://cloud.githubusercontent.com/assets/3852296/13536298/22bf18ea-e265-11e5-9bf8-d7fb92089992.png)
![db3](https://cloud.githubusercontent.com/assets/3852296/13536299/22c18e04-e265-11e5-9128-8714fd9970f0.png)

**Comment by scobbe** [comment]
Ok, thank you for attaching this information. We will look into it further and get back to you with a response.

In the meantime, please confirm that you have done a full 'rebuild' of your project (not 'build') and please confirm that you have restarted your computer (and Visual Studio) as well. Sometimes Visual Studio does not handle the introduction of new packages/files well, and it requires a full system restart for VS to properly register (although this is not too common).

Thank you for your patience!

**Comment by krishnaramuu** [comment]
Did that too, still it is giving the same error.

**Comment by scobbe** [comment]
Alright, thanks for confirming that.

In order for us to debug this issue further, we're going to need to take a look at a minimum reproducible version of your VS project. Please send us a Dropbox shared link pointing to a zipped up edited version of your project. Please either post the Dropbox link here, or if you are not comfortable doing that, please send the link in an API support ticket, which can be created here: https://www.dropbox.com/developers/contact

**Comment by pdfforge** [comment]
is there any update on this issue? It seems that this translates to problems we are having as well (but using Paket as package manager):
https://github.com/fsprojects/Paket/issues/1913

The Paket guys suggest, that you would provide a plain dependecy group definition for .Net 4 instead of mixing it with portable an phone.

Would it be possible to add that as separate dependecy group? I think that it would solve both problems at once.

**Comment by qimingyuan** [comment]
@pdfforge It seems unnecessary to create multiple groups for legacy frameworks. Since this is supported by nuget, I feel it more like a bug on Packet side.

**Comment by pdfforge** [comment]
Well, it is linked to a bug or not implemented feature in Paket, but there is more to it. For example, the version that could work is based on the portable .Net 4.0, not on the "real" Framework. Furthermore the package is built in a strange way, with old versions of the dependencies declared as reference and newer versions actually used. This requires binding redirects on top, which you can only do with applications, not libraries. With the current state, it is effectively impossible to compile a strong-named library on .Net 4.0 that references the Dropbox API (which is, unfortunately, what we have to do...)

And it's not that it would be impossible to implement. We acutally performed the required changes on the source for a test. And even though we all hope that XP support will be not a matter anymore in the future, the reality is a different story right now.

**Comment by qimingyuan** [comment]
Could you let us know which dependency uses newer version than declared and requires binding redirect?

**Comment by qimingyuan** [comment]
Close this one as it has been inactive for almost 2 years.
