### ISSUE TITLE
Is the sdk production ready?

### ISSUE THREAD

**Issue by prakashguru** [dropbox/dropbox-sdk-dotnet#18]
Hi,

The dropbox documentation on the following page mentioned that this sdk is in beta. 
https://www.dropbox.com/developers/documentation/dotnet 

Is it production ready?

**Comment by qimingyuan** [comment]
Yes the SDK is already out of beta and is production ready.

**Comment by GOneKumar** [comment]
Hi there,
We want to use latest V2 APIs in production, but because of its preview state we are still waiting.

The github page [ ](https://github.com/dropbox/dropbox-sdk-dotnet) comment says, the API is still in preview state => '.Net SDK for the Dropbox API v2 preview.'.
Also, this page( June 23, 2015) [](https://blogs.dropbox.com/developers/2015/06/introducing-a-preview-of-the-new-dropbox-net-sdk-for-api-v2/) says 'Please keep in mind that both the SDK and API v2 are in preview mode so please don’t use them for your production apps just yet.'
So, please let us know, shall we wait or start using V2 APIs?
Which Release version shall we use?

**Comment by greg-db** [comment]
@GOneKumar The .NET SDK is no longer a preview and is ready for production. The README is a bit out of date, so we'll get that updated. Also, that blog post is old and doesn't reflect the current state of the SDK.

**Comment by GOneKumar** [comment]
Thank you very much, Greg K.
