### ISSUE TITLE
Dropbox dotnet API documentation is unavailable

### ISSUE THREAD

**Issue by havokentity** [dropbox/dropbox-sdk-dotnet#311]
The dropbox dotnet API documentation link is broken or unavailable.

Any idea when this will be fixed?

[](https://dropbox.github.io/dropbox-sdk-dotnet/html/R_Project_DotNetApiDocumentation.htm)

**Comment by greg-db** [comment]
Thanks for the note! We've recently updated the docs so [the link](https://dropbox.github.io/dropbox-sdk-dotnet/) changed, and we've already updated the link in the readme, so that will be updated in the next build of the docs on GitHub Pages.

And you can access the specific method and class information for the SDK from the "[API Documentation](https://dropbox.github.io/dropbox-sdk-dotnet/gh-pages/obj/api/Dropbox.Api.html)" link at the top of the page.
