### ISSUE TITLE
how sync files?

### ISSUE THREAD

**Issue by ghiboz** [dropbox/dropbox-sdk-dotnet#33]
hi all!
i'm developing an app that would sync some folder into a local copy: reading the samples I've seen how to do to read the filelist and download it, but not how to understand if some file is changed or deleted or new since last sync...

thanks in advance

**Comment by cakoose** [comment]
[`/list_folder`](https://www.dropbox.com/developers/documentation/http/documentation#files-list_folder) is probably what you want.  In addition to returning the list of folders, it returns a "cursor".  Pass that cursor into [`/list_folder/continue`](https://www.dropbox.com/developers/documentation/http/documentation#files-list_folder-continue) to get a list of what has changed since you made the first call.

`/list_folder/continue` also returns a newer cursor, so you can keep calling it with the latest cursor and you'll keep getting a list of what has changed since your last call.

To avoid polling, use [`/list_folder/longpoll`](https://www.dropbox.com/developers/documentation/http/documentation#files-list_folder-longpoll).  That's an HTTP long-polling endpoint that will notify you if anything changes.  (Note: the current implementation isn't precise; it will say "something changed" even if the change wasn't in the folder you're interested in.)

**Comment by ghiboz** [comment]
thanks @cakoose !
but i'm using a `var list = await dbx.Files.ListFolderAsync("/Night_Build", true);`
that retrieve the complete list and  after  i download each file...
like this:
https://github.com/dropbox/dropbox-sdk-dotnet/blob/master/Examples/SimpleTest/Program.cs#L264

**Comment by cakoose** [comment]
`ListFolderAsync` doesn't always give you the complete list; it gives you the first page.  For very large folders, there will be multiple pages (`list.HasMore` will be true).  In that case, you should take `list.Cursor` and pass it to `ListFolderContinueAsync` to get the next page of results.

This same mechanism can be used to retrieve the list of files that have changed.  Take the last `Cursor` value you got and pass it to `ListFolderContinueAsync`.  You'll get back the list of files that have changed.

**Comment by ghiboz** [comment]
ok! thanks @cakoose ! now seems more clear! thanks, i'll check!

**Comment by ghiboz** [comment]
and last question: `ListFolderContinueAsync` mantains the same base folder used for `ListFolderAsync` ?

**Comment by cakoose** [comment]
Yes.  It is encoded in the cursor.

**Comment by ghiboz** [comment]
whoa! that's cool and i'm reaching to obtain what I wish..
thanks for dropbox! :+1:
