### ISSUE TITLE
ListFolderResult / MetaData not flagging if deleted items are files or folders.

### ISSUE THREAD

**Issue by ghostseven** [dropbox/dropbox-sdk-dotnet#67]
When returning ListFolderResult, or more specifically the MetaData inside ListFolderResult.Entries, if the item in question is marked as IsDeleted then both IsFolder and IsFile are both marked as FALSE, making it impossible to determine if the deleted item is a file or folder.  

If the item is not marked as IsDeleted then IsFolder and IsFile are correctly set.

I assume this is not by design but a bug.  

Can anyone replicate this and confirm / fix. Or if this is by design how would you determine between a deleted file and a deleted folder?

**Comment by greg-db** [comment]
This is the expected behavior. The `IsDeleted`, `IsFile`, and `IsFolder` methods allow you to check which subclass a particular [`Metadata`](https://dropbox.github.io/dropbox-sdk-dotnet/html/T_Dropbox_Api_Files_Metadata.htm) object is. That is, it will be only one of [`DeletedMetadata`](https://dropbox.github.io/dropbox-sdk-dotnet/html/T_Dropbox_Api_Files_DeletedMetadata.htm), [`FileMetadata`](https://dropbox.github.io/dropbox-sdk-dotnet/html/T_Dropbox_Api_Files_FileMetadata.htm), or [`FolderMetadata`](https://dropbox.github.io/dropbox-sdk-dotnet/html/T_Dropbox_Api_Files_FolderMetadata.htm) respectively. 

The API doesn't offer the ability to tell if a [`DeletedMetadata`](https://dropbox.github.io/dropbox-sdk-dotnet/html/T_Dropbox_Api_Files_DeletedMetadata.htm) was previously for a folder or a file, but I'll pass this along as a feature request.

Note that the path for any particular [`DeletedMetadata`](https://dropbox.github.io/dropbox-sdk-dotnet/html/T_Dropbox_Api_Files_DeletedMetadata.htm) could have referred to both a file and folder at different points in the past though, so you can check the file revisions or the metadata your app previously received for more information, depending on what your app is looking for exactly.
