### ISSUE TITLE
Request Authorize Page, SIGN IN button disabled

### ISSUE THREAD

**Issue by navia-ang** [dropbox/dropbox-sdk-dotnet#71]
I've making "Dropbox App Type" using this SDK 
and its work when authorize, delete file, create folder, download and upload.

But today my login page Login Button Disabled.
- I'm using WebBrowser Component form Visual Studio 2015.
- IE version 11

![image](https://user-images.githubusercontent.com/25472899/33597082-d48ff74c-d9d0-11e7-9672-dd345902e7c0.png)

![image](https://user-images.githubusercontent.com/25472899/33597145-0533a72c-d9d1-11e7-86b1-9517dbaa7b31.png)

Upload, Delete work normal. Just Sign In button disabled.
Test on IE using the authorizeUri link, its work normal. 

Thanks for advice.

**Comment by greg-db** [comment]
Thanks for the report. We've looked into this, and unfortunately it seems that the "WebBrowser Component" is actually using an older version of Internet Explorer (effectively IE 9), even though a newer one (IE 11) is installed on the system. 

The older version (IE 9) [isn't officially supported](https://www.dropbox.com/help/desktop-web/system-requirements) by dropbox.com though, so it's not guaranteed to work there.

That being the case, we recommend upgrading the browser control if possible, or more ideally, using the system browser instead of an embedded browser. The latter is our current guidance, per [the OAuth 2 /authorize documentation](https://www.dropbox.com/developers/documentation/http/documentation#oauth2-authorize ).
 (Otherwise, users using the Google Sign In flow may not be able to use your app in the future anyway.)

**Comment by navia-ang** [comment]
Thanks. Solved.
https://stackoverflow.com/questions/17922308/use-latest-version-of-internet-explorer-in-the-webbrowser-control

**Comment by greg-db** [comment]
For reference, this should be working again now. We still recommend using the system browser though for the best compatibility.
