### ISSUE TITLE
InitializeCertPinning breaks HTTPS for non-Dropbox URLs

### ISSUE THREAD

**Issue by BradSmith1985** [dropbox/dropbox-sdk-dotnet#74]
DropboxCertHelper.InitializeCertPinning() method sets the application-wide ServicePointManager.ServerCertificateValidationCallback handler, overriding the default SSL certificate validation logic. This has the potential to break any subsequent web request made to non-Dropbox URLs. The operation will fail with "AuthenticationException: The remote certificate is invalid according to the validation procedure.".

Rather than changing global application behaviour, this method should be rewritten to only affect Dropbox API methods.

**Comment by greg-db** [comment]
Thanks for the report! I'll ask the team to change that accordingly.

**Comment by greg-db** [comment]
@BradSmith1985 I just heard back from the team, and if you're connecting to non-Dropbox URLs, they recommend using [`DropboxCertHelper.IsKnownRootCertPublicKey`](https://dropbox.github.io/dropbox-sdk-dotnet/html/M_Dropbox_Api_DropboxCertHelper_IsKnownRootCertPublicKey_1.htm) directly instead of `InitializeCertPinning`. `IsKnownRootCertPublicKey` allows you to implement [the same](https://github.com/dropbox/dropbox-sdk-dotnet/blob/9803a40b3169acf66a2d14e29af8750ebe6e3e17/dropbox-sdk-dotnet/Dropbox.Api/DropboxCertHelper.cs#L230) certificate pinning as `InitializeCertPinning`, but on an as needed basis.

**Comment by RegisStGelais** [comment]
I'm hitting the same issue. My app implements both Dropbox  and MsGraph (OneDrive)
Where do I fond the public key byte array that DropboxCertHelper.IsKnownRootCertPublicKey requires as  parameter ??

**Comment by greg-db** [comment]
@RegisStGelais I see you opened [a new issue for this](https://github.com/dropbox/dropbox-sdk-dotnet/issues/211), so I'll follow up with you there.
