### ISSUE TITLE
Issue with access token

### ISSUE THREAD

**Issue by NickDevoctomy** [dropbox/dropbox-sdk-dotnet#92]
Hi there,

This may well be a problem with my code, but I'm having an issue with the access token I'm being provided.  I'm using the flow that doesn't require a redirect URI.  Dropbox gives me an access token, which for the moment just to test with, I am putting it to one side.

I'm then using this access token in the constructor of the DropBoxClient,

    DropboxClient _client;
    _client = new DropboxClient(accessToken, new DropboxClientConfig());
    FullAccount full = await _client.Users.GetCurrentAccountAsync();

The above is then resulting in an AuthException, "invalid_access_token".  I'm pretty sure that I've copy and pasted it correctly out of the web page.  There's not much else I can do to simplify my testing further, I'm trying to get the current account just to test the access token.

I've also tried getting some file meta data from my apps path (I'm not requesting full access, only app folder) but this results in the same error.

Path = "/test.txt"

I can't see the path or file in my dropbox at current, so was kind of assuming the app folder would be created when requested?

Nick.

**Comment by NickDevoctomy** [comment]
Just to add to this, If I use the access token generated in the app page for my account, it works.  Just not the one that's being generated for the same user through the app.

**Comment by NickDevoctomy** [comment]
I think I found the issue, I'm creating the login URL using the DropboxOAuth2Helper.GetAuthorizeUri method.  I'm passing my "App Key" into that, is that wrong?  It says ClientID but I'm unsure where to locate that.  (sorry for the flurry of messages)

**Comment by greg-db** [comment]
It sounds like you're using this `GetAuthorizeUri` method, which only requires `clientId`, and not a redirect URI. Your "client ID" is the same as your "app key", so that is the right value to use there. In any case, note that this method uses the "code" OAuth 2 authorization flow.

When using this code flow, the string that is given back to the client, whether via a redirect URI or not, is an "authorization code", not an "access token". Accordingly, attempting to use it as an access token will fail like this.

Whether you're using a redirect URI or not, when using the "code" flow, you need to exchange the authorization code for an access token first. You can do so using [the `ProcessCodeFlow` method](https://dropbox.github.io/dropbox-sdk-dotnet/html/Overload_Dropbox_Api_DropboxOAuth2Helper_ProcessCodeFlowAsync.htm). (The `redirectUri` parmeter is optional.) There's [an example here](https://github.com/dropbox/dropbox-sdk-dotnet/blob/master/dropbox-sdk-dotnet/Examples/SimpleBlogDemo/Controllers/HomeController.cs#L197).

Also, yes, the app folder for app with the "app folder" permission will get created automatically once you link the app to the account. This only occurs once the access token is created, not just the authorization code.

**Comment by NickDevoctomy** [comment]
Excellent, thanks for clarifying that for me, that makes perfect sense. Much appreciated.
